apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: stephengrider/multi-server
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword # Defined name when creating the K8s Secret Object
                key: PGPASSWORD # Key from key=value pair defined inside the Secret Object

        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 5000
