apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1 # this can be supressed. If left blank, only one replica will be created
  selector:
    matchLabels:
      component: worker

  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
      - name: worker
        image: stephengrider/multi-worker
        # Env vars will come here
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"